ktor:
    deployment:
        port: 8080
        host: 0.0.0.0
    application:
        modules:
            - ApplicationKt.module

jwt:
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    realm: ${JWT_REALM}
    secret: ${JWT_SECRET}

supabase:
    url: ${SUPABASE_URL}
    key: ${SUPABASE_KEY}
